### ISSUE TITLE
Connection doesn't be released when callInTransaction with create a list of data

### ISSUE THREAD

**Issue by YangChihLin** [j256/ormlite-core#103]
For some reason we want to create a record as well as a collection of correlated data.
But after we test it, we found that when create a list of data could not release the connection.
```
// do stuff
try {
      synchronized (TransactionManager.class) {        
        return TransactionManager.callInTransaction(DataBaseService.getInstance().getConnSource(),
            getCreateCallable(aList));
      }
    } catch (SQLException e) {
      LOGGER.error(e);
    }

...
```
while the getCreateCallable method return a Callable like:
...
```
 Callable<Boolean> callable = () -> {
    // do stuff but we know that is irrelative after tested.
    return dao.create(aList) >= 0;
  };
```
also, HikariCP's connection leak detection show this warning for us:
```
2017-04-08T23:19:12.113 1491664752113 SIP [WARN] NA NA NA NA com.zaxxer.hikari.pool.ProxyLeakTask.run(ProxyLeakTask.java:90) Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@57ac5227, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.j256.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:147)
	at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:166)
	at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:150)
```

we are using :
ormlite-jdbc 5.0 
HikariCP 2.6.1
MySQL 5.6

Is the information enough to figure out what's going on with that?

**Comment by YangChihLin** [comment]
After I change my code to using for loop to create each of data, then every thing is work, no more connection held.

here is my code:
```
      //this is fine
      int succRows =0;
      for (QueueMember qm : coll) {
        succRows += queueMemberDao.create(qm);
      }

      // this is original what I want to do
      succRows= dao.create(coll);
```

by the way, my QueueMember.class shown as bellow.
```
@DatabaseTable(tableName = "queue_member")
public class QueueMember {
  @DatabaseField(generatedId = true)
  private Integer uniqueid;
  @DatabaseField
  private String membername;
  @DatabaseField(columnName = "queue_name")
  private String queue_name;
  @DatabaseField(columnName = "interface")
  private String Interface; // interface是保留字，用大寫
  @DatabaseField
  private Integer penalty; // 0
  @DatabaseField
  private Integer paused;

  public QueueMember() {}

  // getter & setter
```
and my dao class:

```

public class QueueMemberDao extends BaseDaoImpl<QueueMember, Integer> {

  private static QueueMemberDao self;

  private QueueMemberDao(ConnectionSource connectionSource, Class<QueueMember> dataClass)
      throws SQLException {
    super(connectionSource, dataClass);
  }

  public static QueueMemberDao getDao() throws SQLException {
    if (self == null) {
   
      self = new QueueMemberDao(DataBaseService.getInstance().getConnSource(),
          QueueMember.class);
    }
    return self;
  }

```

**Comment by j256** [comment]
Sorry for the delay on this.  I just can't reproduce this.  The code to release the connection is in a try/finally.  Can you take a look at the test to see if you can figure out how it is different from your's?  Thanks.   See https://github.com/j256/ormlite-core/blob/master/src/test/java/com/j256/ormlite/misc/TransactionManagerTest.java#L349

**Comment by Nyderx** [comment]
Hi,

I have recently met probably the same problem, so maybe I will shed some light on that.
What I do is calling batch tasks during callInTransaction. Batch tasks are also called during create(Collection) in BaseDaoImpl, so it is the same problem as the one indicated by YangChihLin.

My simple example looks that:
```
 public void example(final JdbcPooledConnectionSource connection, final Dao<String, Integer> dao) throws SQLException {
        TransactionManager.callInTransaction(connection, () -> {
            dao.callBatchTasks(() -> {
                // some dao task
                return null;

            });
            return null;
        });
    }
```

Till now it looks the same as in the test provided by you, j256. The difference is in used connection source. I use JdbcPooledConnectionSource and executing above example with that connection source leads to connection leak. The test uses single connection source and that's why it passes.

I have spent some time investigating the problem with the debugger. I found the bug reason and I will try to show it here.

First let's see code which calls transaction and batch task. Take a special look at saving and releasing special connection.
1) TransactionManager
```
	public static <T> T callInTransaction(String tableName, final ConnectionSource connectionSource,
			final Callable<T> callable) throws SQLException {

		DatabaseConnection connection = connectionSource.getReadWriteConnection(tableName);
		try {
			boolean saved = connectionSource.saveSpecialConnection(connection);
			return callInTransaction(connection, saved, connectionSource.getDatabaseType(), callable);
		} finally {
			// we should clear aggressively
			connectionSource.clearSpecialConnection(connection);
			connectionSource.releaseConnection(connection);
		}
	}
```
```
2) BaseDaoImpl
	private <CT> CT doCallBatchTasks(ConnectionSource connectionSource, Callable<CT> callable) throws SQLException {
		boolean saved = false;
		DatabaseConnection connection = connectionSource.getReadWriteConnection(tableInfo.getTableName());
		try {
			 (...)
			saved = connectionSource.saveSpecialConnection(connection);
			return doCallBatchTasks(connection, saved, callable);
		} finally {
			if (saved) {
				connectionSource.clearSpecialConnection(connection);
			}
			connectionSource.releaseConnection(connection);
			(...)
		}
	}
```

As we can see in (1) before transaction we save special connection and after transaction we always clear it and then release.
In (2) we call save special connection, but we clear it only if method connectionSource.saveSpecialConnection() returns true.

Now let's take a look at saveSpecialConnection in JdbcPooledConnectionSource.
3. JdbcPooledConnectionSource
```
	public boolean saveSpecialConnection(DatabaseConnection connection) throws SQLException {
		checkInitializedIllegalStateException();
		boolean saved = saveSpecial(connection);
		(...)
		return saved;
	}
```
And at saveSpecial in BaseConnectionSource:
4. BaseConnectionSource
```
	protected boolean saveSpecial(DatabaseConnection connection) throws SQLException {
		// check for a connection already saved
		NestedConnection currentSaved = specialConnection.get();
		if (currentSaved == null) {
			specialConnection.set(new NestedConnection(connection));
			return true;
		} else {
			if (currentSaved.connection != connection) {
				throw new SQLException("trying to save connection " + connection
						+ " but already have saved connection " + currentSaved.connection);
			}
			// we must have a save call within another save
			currentSaved.increment();
			return false;
		}
	}
```

What we can notice is that when we give already saved connection to saveSpecial() method, it will increment currentSaved value and return **false**. This **false** means that we do not call clearSpecialConnection in callBatchTask (2).

Let's see this step by step.
0. currentSaved = 0
1. callInTransaction - saveSpecialConnection => currentSaved = 1, saveSpecialConnection() returns true
2. callBatchTask - saveSpecialConnection => currentSaved = 2, saveSpecialConnection() returns **false**
3. callBatchTask - clearSpecialConnection - **not called because we got false from point 2**
4. callBatchTask - releaseConnection => currentSaved > 0, do nothing
4. callInTransaction - clearSpecialConnection => currentSaved = 1
5. callInTransaction - releaseConnection => currentSaved > 0, do nothing

This way the connection is never released. In app which I develop, we do each transaction in new thread, so this bug leads to serious database error (too many connections).

Please let me know if my explanation is clear and if there are some chances to fix this bug in next releases.

**Comment by j256** [comment]
Thanks for the details @Nyderx !

**Comment by j256** [comment]
For the record, the 5.2 release just pushed out has some fixed to the TransactionManager which may resolve this issue. Feedback welcome. See: 74ceed2
