### ISSUE TITLE
upgrade log4j2 dependency

### ISSUE THREAD

**Issue by muzammil360** [j256/ormlite-core#259]
Hi. I noticed that you have upgraded log4j2 dependency to latest version here: https://github.com/j256/ormlite-core/blob/43f7a51f0dc845be7e18fef46fb8fc8c15426f89/pom.xml#L56

I didn't find any issue discussing about the steps we are taking to address this issue in `ormlite-core`. This issue might serve the purpose. When are we planning to have a release that includes above changes?

**Comment by j256** [comment]
ormlite doesn't have a direct dependency on log4j2 @muzammil360 .  It just uses simplelogging which is a shim that can backend to a wide variety of log systems including log4j2. This change was done by the dependabot.  I'm not 100% sure what I'm going to do with the log4j2 dependency because 2.17.0 is java 8 only and ormlite-core still supports java 7.

**Comment by j256** [comment]
Thanks for the poke.  Ormlite wasn't directly affected but at best it was confusing.  Just bumped log4j2 to 2.17.0 to remove any confusion and changed from provided to optional which it should have been before.  Thanks.
